prompt --application/shared_components/email/templates/reset_password
begin
--   Manifest
--     REPORT LAYOUT: RESET PASSWORD
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>215941952601575223
,p_default_application_id=>216
,p_default_id_offset=>0
,p_default_owner=>'JGOLON'
);
wwv_flow_api.create_email_template(
 p_id=>wwv_flow_api.id(56670787910763930)
,p_name=>'RESET PASSWORD'
,p_static_id=>'RESET_PASSWORD'
,p_subject=>'Recover Password'
,p_html_body=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<table class="row row-2" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">',
'						<tbody>',
'							<tr>',
'								<td>',
'									<table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 600px;" width="600">',
'										<tbody>',
'											<tr>',
'												<td class="column column-1" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; background-color: #f4f4f4; padding-left: 10px; padding-right: 10px; padding-top: 10px; '
||'padding-bottom: 20px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">',
'													<table class="text_block" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">',
'														<tr>',
'															<td>',
'																<div style="font-family: sans-serif">',
'																	<div class="txtTinyMce-wrapper" style="font-size: 14px; mso-line-height-alt: 16.8px; color: #000000; line-height: 1.2; font-family: Helvetica Neue, Helvetica, Arial, sans-serif;">',
'																		<p style="margin: 0; font-size: 14px; text-align: center;">This link will expire in the next 30 minutes.<br><br></p>',
'																	</div>',
'																</div>',
'															</td>',
'														</tr>',
'													</table>',
'												</td>',
'											</tr>',
'										</tbody>',
'									</table>',
'								</td>',
'							</tr>',
'						</tbody>',
'					</table>',
'				</td>',
'			</tr>',
'		</tbody>',
'	</table><!-- End -->',
'</body>',
'',
'</html>'))
,p_html_header=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!DOCTYPE html>',
'<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en">',
'',
'<head>',
'	<title></title>',
'	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">',
'	<meta name="viewport" content="width=device-width, initial-scale=1.0">',
'	<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->',
'	<!--[if !mso]><!-->',
'	<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">',
'	<link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet" type="text/css">',
'	<!--<![endif]-->',
'	<style>',
'		* {',
'			box-sizing: border-box;',
'		}',
'',
'		body {',
'			margin: 0;',
'			padding: 0;',
'		}',
'',
'		a[x-apple-data-detectors] {',
'			color: inherit !important;',
'			text-decoration: inherit !important;',
'		}',
'',
'		#MessageViewBody a {',
'			color: inherit;',
'			text-decoration: none;',
'		}',
'',
'		p {',
'			line-height: inherit',
'		}',
'',
'		.desktop_hide,',
'		.desktop_hide table {',
'			mso-hide: all;',
'			display: none;',
'			max-height: 0px;',
'			overflow: hidden;',
'		}',
'',
'		@media (max-width:620px) {',
'			.row-content {',
'				width: 100% !important;',
'			}',
'',
'			.mobile_hide {',
'				display: none;',
'			}',
'',
'			.stack .column {',
'				width: 100%;',
'				display: block;',
'			}',
'',
'			.mobile_hide {',
'				min-height: 0;',
'				max-height: 0;',
'				max-width: 0;',
'				overflow: hidden;',
'				font-size: 0px;',
'			}',
'',
'			.desktop_hide,',
'			.desktop_hide table {',
'				display: table !important;',
'				max-height: none !important;',
'			}',
'		}',
'	</style>',
'</head>',
'',
'<body style="background-color: #ffffff; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;">',
'	<table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;">',
'		<tbody>',
'			<tr>',
'				<td>',
'					<table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto;">',
'						<tbody>',
'							<tr>',
'								<td>',
'									<table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto; color: #000000; width: 600px;" width="600">',
'										<tbody>',
'											<tr>',
'												<td class="column column-1" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; background-color: #f4f4f4; padding-left: 50px; padding-right: 50px; padding-top: 15px; '
||'padding-bottom: 15px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">',
'													<table class="text_block" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">',
'														<tr>',
'															<td>',
'																<div style="font-family: sans-serif">',
'																	<div class="txtTinyMce-wrapper" style="font-size: 14px; mso-line-height-alt: 16.8px; color: #000000; line-height: 1.2; font-family: Helvetica Neue, Helvetica, Arial, sans-serif;">',
'																		<p style="margin: 0; font-size: 14px;"><strong><span style="font-size:38px;">Forgot your password?</span></strong></p>',
'																	</div>',
'																</div>',
'															</td>',
'														</tr>',
'													</table>',
'													<table class="text_block" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">',
'														<tr>',
'															<td>',
'																<div style="font-family: sans-serif">',
'																	<div class="txtTinyMce-wrapper" style="font-size: 14px; mso-line-height-alt: 16.8px; color: #000000; line-height: 1.2; font-family: Helvetica Neue, Helvetica, Arial, sans-serif;">',
'																		<p style="margin: 0; font-size: 14px;"><span style="font-size:16px;">Hey, we received a request to reset your password.</span></p>',
'																	</div>',
'																</div>',
'															</td>',
'														</tr>',
'													</table>',
'													<table class="text_block" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">',
'														<tr>',
'															<td>',
'																<div style="font-family: sans-serif">',
'																	<div class="txtTinyMce-wrapper" style="font-size: 14px; mso-line-height-alt: 16.8px; color: #000000; line-height: 1.2; font-family: Helvetica Neue, Helvetica, Arial, sans-serif;">',
'																		<p style="margin: 0; font-size: 14px;"><span style="font-size:16px;">To reset your password, click the following link and follow the instructions</span></p>',
'																	</div>',
'																</div>',
'															</td>',
'														</tr>',
'													</table>',
'													<table class="button_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">',
'														<tr>',
'															<td style="padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:20px;text-align:center;">',
'																<div align="center">',
'																	<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="#LINK_TO#" style="height:48px;width:480px;v-text-anchor:middle;" arcsize="34%" stroke="false" fillcolor="#e65959"'
||'><w:anchorlock/><v:textbox inset="5px,0px,0px,0px"><center style="color:#ffffff; font-family:Arial, sans-serif; font-size:15px"><![endif]--><a href="#LINK_TO#" target="_blank" style="text-decoration:none;display:block;color:#ffffff;background-color:#'
||'e65959;border-radius:16px;width:100%; width:100%;border-top:0px solid TRANSPARENT;font-weight:400;border-right:0px solid TRANSPARENT;border-bottom:0px solid TRANSPARENT;border-left:0px solid TRANSPARENT;padding-top:8px;padding-bottom:8px;font-family:'
||'Helvetica Neue, Helvetica, Arial, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:25px;padding-right:20px;font-size:15px;display:inline-block;letter-spacing:normal;"><span style="font-size: 16px; line-'
||'height: 2; word-break: break-word; mso-line-height-alt: 32px;"><span style="font-size: 15px; line-height: 30px;" data-mce-style="font-size: 15px; line-height: 30px;"><strong>RESET MY PASSWORD</strong></span></span></span></a>',
'																	<!--[if mso]></center></v:textbox></v:roundrect><![endif]-->',
'																</div>',
'															</td>',
'														</tr>',
'													</table>',
'													<table class="text_block" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">',
'														<tr>',
'															<td>',
'																<div style="font-family: sans-serif">',
'																	<div class="txtTinyMce-wrapper" style="font-size: 14px; mso-line-height-alt: 16.8px; color: #000000; line-height: 1.2; font-family: Helvetica Neue, Helvetica, Arial, sans-serif;">',
'																		<p style="margin: 0; font-size: 14px;">If you didn''t request a password reset, you can ignore this message. Your password will no be changed</p>',
'																	</div>',
'																</div>',
'															</td>',
'														</tr>',
'													</table>',
'												</td>',
'											</tr>',
'										</tbody>',
'									</table>',
'								</td>',
'							</tr>',
'						</tbody>',
'					</table>'))
);
wwv_flow_api.component_end;
end;
/
